<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>WhereWindsMeetLaunchCapture</AssemblyName>
    <RootNamespace>WhereWindsMeetLaunchCapture</RootNamespace>
    <ApplicationIcon>..\..\src\yysls.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.1.0</Version>
  </PropertyGroup>
</Project>
